### ISSUE TITLE
TypeScript support tracking issue

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-js#79]
Scoping this out, seems totally possible for this lib to be converted to typescript.

Unsure of the overhead of allowing contracts to be ts since it seems the pattern is to just use this library, but this is what the path seems to look like:

*   [x] Switch near-sdk-js to typescript (#82)
*   [x] Add support into JS CLI to build typescript contracts? (this one is a bit unclear because there is some convoluted logic in there)
*   [ ] Switch some or all examples to TS

Options for adding support to SDK CLI to build typescript contracts intuitively to me are:

*   Conditionally use the [typescript plugin for rollup](https://www.npmjs.com/package/@rollup/plugin-typescript) to be able to compile ts contract file 
      *   This would require checking the input file name for the type to be able to include typescript plugin or not – maybe both `index.js` and `index.ts` are checked for existence? Otherwise, someone doing ts contracts will just have to specify the `source` argument to the ts file.
*   Modify CLI to compile the TS contract file to ESM JS and use that file in the rollup
*   Don't change any tooling, developers can compile ts to JS themselves and just update the `source` argument to this file

**Comment by ailisp** [comment]
To be clear, SDK can be written with TS (or JS + typedefs), but from the original requirement, we must not limit user to write contract with TypeScript (not near-sdk-ts)

**Comment by austinabell** [comment]
> To be clear, SDK can be written with TS (or JS + typedefs), but from the original requirement, we must not limit user to write contract with TypeScript (not near-sdk-ts)

Yes, but having the option to write a contract in typescript is what is being referred to here. Thanks for making that point clear

**Comment by ailisp** [comment]
> Add support into JS CLI to build typescript contracts

is added in #134 

> Switch some or all examples to TS

Had a first example in TS in #134. More examples are discussed offline and we plan to create issue per example to track
